name: 'Chromatic'

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    if: !contains(github.event.head_commit.message , 'dependabot')
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.7.4
      - run: pnpm i --frozen-lockfile
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          buildScriptName: 'build-storybook'
