name: 'Chromatic'

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.7.4
      - run: pnpm i --frozen-lockfile
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          buildScriptName: 'build-storybook'
